source 'https://github.com/CocoaPods/Specs.git'
#source 'https://github.com/ios-3ds-sdk/Specs.git'
#source 'https://github.com/primer-io/primer-podspecs.git'

use_frameworks!

platform :ios, '11.0'

target 'Primer3DS_Example' do
  pod 'Primer3DS' , :path => '../'
#  pod 'Primer3DS'
#  pod 'ThreeDS_SDK'
end
