default_platform(:ios)

#----------------------- CONSTANTS -------------------------#

# Github
github_run_id = ENV["GITHUB_RUN_ID"]
github_run_number = ENV["GITHUB_RUN_NUMBER"]

# Xcode
app_workspace = "Example/Primer3DS.xcworkspace"
app_xcode_proj = "Example/Primer3DS.xcodeproj"
app_scheme = "Primer3DS-Example"

# Utils
sdk_version_name_source_branch = ENV['SOURCE_BRANCH']
pr_number = ENV['PR_NUMBER']

ENV["FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT"] = "120"

#--------------------- END CONSTANTS -----------------------#

#----------------------- FASTLANE -------------------------#

platform :ios do

###################### PUBLIC LANES #######################

  lane :tests do
    run_tests(workspace: app_workspace, 
              scheme: "Primer3DS-Example",
              destination: "platform=iOS Simulator,name=iPhone 14 Pro",
              xcargs: "EXCLUDED_ARCHS[sdk=iphonesimulator*]=arm64")
  end

  lane :build do
    common_pre_build_action

    cocoapods(
      clean_install: true,
      use_bundle_exec: true,
      podfile: "Example/Podfile"
    )

    # Build for browserstack
    xcodebuild(
      scheme: app_scheme,
      workspace: app_workspace,
      configuration: "Debug",
      include_bitcode: false,
      build: true,
      destination: "generic/platform=iOS",
      skip_package_dependencies_resolution: true,
      build_settings: {
        "CODE_SIGNING_REQUIRED" => "NO",
        "CODE_SIGN_IDENTITY" => ""
      }
    )
  end

  lane :build_and_test do 
    build
    tests
  end

  ######################### PRIVATE LANES #########################

  desc 'Common build pre-action'
  private_lane :common_pre_build_action do

    set_version_and_build_number

    # setup_signing(
    #   match_type: "development"
    # )

  end

  desc 'This action creates a temporary keychain and installs certificates and provisioning profiles'
  private_lane :setup_signing do |options|

    create_keychain(
      name: ENV["MATCH_KEYCHAIN_NAME"],
      password: ENV["MATCH_KEYCHAIN_PASSWORD"],
      default_keychain: true,
      unlock: true,
      timeout: 3600,
      lock_when_sleeps: true
    )

    match(
      type: options[:match_type],
      readonly: true,
      keychain_name: ENV["MATCH_KEYCHAIN_NAME"],
      keychain_password: ENV["MATCH_KEYCHAIN_PASSWORD"],
    )

  end

  desc 'This action sets the version and build number'
  private_lane :set_version_and_build_number do

    # We don't really need the version number
    # at this moment.
    # The Build number is the unique identifier of the package
    # matching the Github Workflow run ID and number

    # Set version number
    # increment_version_number(
    #   version_number: sdk_version_name_source_branch,
    #   xcodeproj: app_xcode_proj
    # )

    # Set build number
    increment_build_number(
      build_number: "#{github_run_id}.#{github_run_number}",
      xcodeproj: app_xcode_proj
    )

  end

  ################## END PRIVATE LANES ######################

end

#--------------------- END FASTLANE ------------------------#
