name: Build and test

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  danger:
    runs-on: ubuntu-latest
    name: "Run Danger"
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - name: Danger
        uses: docker://ghcr.io/danger/danger-swift@sha256:2e44d105d03a4282d8e7ea9a770d7393585ea2337a09bc4f1e3b49003ad4e7b1 # 3.13.0
        with:
            args: --failOnErrors --no-publish-check --remove-previous-comments
        env:
          GITHUB_TOKEN: ${{ github.token }}
  build-and-test:
    needs: danger
    runs-on: macos-13
    timeout-minutes: 20
    name: "Build and test"
    steps:
      - name: Cancel previous jobs
        uses: styfle/cancel-workflow-action@b173b6ec0100793626c2d9e6b90435061f4fc3e5 # 0.11.0
        with:
          access_token: ${{ github.token }}

      - name: Git - Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          ref: ${{ github.ref }}

      - name: Select Xcode Version
        uses: maxim-lobanov/setup-xcode@60606e260d2fc5762a71e64e74b2174e8ea3c8bd # v1.6.0
        with:
          xcode-version: '15.0' 

      # - name: Install SSH key
      #   uses: shimataro/ssh-key-action@v2
      #   with:
      #     key: ${{ secrets.SSH_KEY }}
      #     name: id_rsa_github_actions
      #     known_hosts: ${{ secrets.KNOWN_HOSTS }}

      # - uses: webfactory/ssh-agent@v0.7.0
      #   with:
      #     ssh-private-key: ${{ secrets.SSH_KEY }}

      - uses: ruby/setup-ruby@22fdc77bf4148f810455b226c90fb81b5cbc00a7 # v1.172.0
        with:
          ruby-version: "3.2.2"
          bundler-cache: true
          
      - name: Setup node
        uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7 # v3.8.2
        with:
          node-version: 18.3.0

      - run: npm install --save slack-message-builder

      - name: Test & Build 🚀
        run: |
          bundle exec fastlane unit_tests
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          MATCH_GIT_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
          FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
          FASTLANE_SESSION: ${{ secrets.FASTLANE_SESSION }}
          MATCH_KEYCHAIN_NAME: ${{ secrets.MATCH_KEYCHAIN_NAME }}
          MATCH_KEYCHAIN_PASSWORD: ${{ secrets.MATCH_KEYCHAIN_PASSWORD }}
          APPETIZE_API_TOKEN: ${{ secrets.APPETIZE_API_TOKEN }}
          SOURCE_BRANCH: ${{ github.head_ref }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          
      # - name: Create Slack Success Summary Report
      #   if: ${{ success() && github.event.pull_request.base.ref == 'master'  }}
      #   run: |
      #     node Report\ Scripts/appetize-success-report-script.js createAppetizeSummaryReport ${{ github.head_ref || github.ref_name }}
      # - name: Slack Success Notification
      #   if: ${{ success() && github.event.pull_request.base.ref == 'master' }}
      #   uses: slackapi/slack-github-action@v1.23.0
      #   with:
      #     channel-id: ${{ secrets.SLACK_MOBILE_SDK_CHANNEL }}
      #     payload-file-path: '/var/tmp/appetize-success-link-summary.json'
      #   env:
      #     SLACK_BOT_TOKEN: ${{ secrets.SLACK_REPORTER_BOT_TOKEN }}

      # - name: Create Slack Failure Summary Report
      #   if: ${{ failure() && github.event.pull_request.base.ref == 'master' }}
      #   run: |
      #     node Report\ Scripts/appetize-failure-report-script.js createAppetizeSummaryReport ${{ github.head_ref || github.ref_name }}
      # - name: Slack Notification
      #   if: ${{ failure() && github.event.pull_request.base.ref == 'master' }}
      #   uses: slackapi/slack-github-action@v1.23.0
      #   with:
      #     channel-id: ${{ secrets.SLACK_MOBILE_SDK_CHANNEL }}
      #     payload-file-path: '/var/tmp/appetize-failure-link-summary.json'
      #   env:
      #     SLACK_BOT_TOKEN: ${{ secrets.SLACK_REPORTER_BOT_TOKEN }}
