name: Create Release

on:
  workflow_dispatch:
    inputs:
      releaseType:
        description: 'Release Type'
        required: true
        type: choice
        options:
          - default
          - alpha
          - beta
          - rc

jobs:
  bump-version:
    runs-on: ubuntu-latest
    name: "Bump release version and create changelog"
    steps:
      - name: Check out repo
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          fetch-depth: 0
          token: ${{ secrets.RELEASE_ACCESS_TOKEN }}
      - name: Install cz
        run: pip install --user -U Commitizen
      - name: Record from version
        run: |
          echo "FROM_VERSION=$(cz version --project)" >> $GITHUB_ENV
      - name: Create release branch
        run: |
          git checkout -b release/next
          git push -u origin release/next
      # Bump version and create CHANGELOG - default release
      - name: Create bump and changelog
        if: ${{ inputs.releaseType == 'default' }}
        run: cz bump --files-only --yes --changelog
      # Bump version and create CHANGELOG - prereleasee
      - name: Create bump and changelog
        if: ${{ inputs.releaseType != 'default' }}
        run: cz bump --files-only --yes --changelog --prerelease ${{ inputs.releaseType }}
      - name: Record to version
        run: |
          echo "TO_VERSION=$(cz version --project)" >> $GITHUB_ENV
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@153407881ec5c347639a548ade7d8ad1d6740e38 # v5.0.2
        with:
          token: ${{ secrets.RELEASE_ACCESS_TOKEN }}
          base: main
          branch: release/next
          delete-branch: true
          title: Release ${{ env.TO_VERSION }}
          body: 'Bumped ${{ env.FROM_VERSION}} -> ${{ env.TO_VERSION }}'
